package Componentes.CRUD;

import Administrador.Regiones;
import Administrador.ctrlRegiones;
import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mesoi
 */
public class AdminAgregarRegiones extends javax.swing.JPanel {

    private DefaultTableModel modelo;
    private ArrayList<Regiones> totalRegiones;

    /**
     * Creates new form AdminAgregarRegiones
     */
    public AdminAgregarRegiones() {
        initComponents();
        this.setBounds(0, 0, 700, 455);
        modelo = (DefaultTableModel) tabla1.getModel();
        lblPrecioEspecial.setText("");
        lblPrecioEstandar.setText("");
        cargarRegiones();
    }

    public void cargarRegiones() {
        modelo.setRowCount(0);
        totalRegiones = (ArrayList<Regiones>) ctrlRegiones.getTodasRegiones().clone();
        for (Regiones Region : totalRegiones) {
            Object datos[] = new Object[4];
            datos[0] = Region.getCodigo();
            datos[1] = Region.getNombre();
            datos[2] = Region.getPrecioEstandar();
            datos[3] = Region.getPrecioEspecial();
            modelo.addRow(datos);
        }
    }

    public void agregarRegion() {
        Pattern vPrecio = Pattern.compile("^[0-9]+\\.?[0-9]*$");
        Matcher m = vPrecio.matcher(txtPrecioEst.getText());
        Matcher m1 = vPrecio.matcher(txtPrecioEspe.getText());

        if (!txtCodigo.getText().toString().equals("") && !txtNombreR.getText().toString().equals("") && !txtPrecioEspe.getText().toString().equals("") && !txtPrecioEst.getText().toString().equals("")) {
            if (!m.find()) {
                JOptionPane.showMessageDialog(null, "El precio Estandar no es un precio valido");
                return;
            }
            if (!m1.find()) {
                JOptionPane.showMessageDialog(null, "El precio Especial no es un precio valido");
                return;
            }
            
            if (ctrlRegiones.nuevaRegion(txtCodigo.getText().toString(), txtNombreR.getText().toString(), Double.parseDouble(txtPrecioEst.getText()), Double.parseDouble(txtPrecioEspe.getText()))) {
                JOptionPane.showMessageDialog(null, "Region ingresada con exito");
                limpiartxts();
                cargarRegiones();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Falatan campos por llenar");
        }

    }
    
    public void limpiartxts(){
        txtCodigo.setText("");
        txtNombreR.setText("");
        txtPrecioEspe.setText("");
        txtPrecioEst.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDark1 = new Elementos.CutomTable.TableDark();
        panelRound1 = new Elementos.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        panelRound2 = new Elementos.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioEst = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioEspe = new javax.swing.JTextField();
        lblPrecioEstandar = new javax.swing.JLabel();
        lblPrecioEspecial = new javax.swing.JLabel();
        buttonRound1 = new Elementos.ButtonRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new Elementos.CutomTable.TableDark();

        tableDark1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDark1);

        setOpaque(false);

        panelRound1.setBackground(new java.awt.Color(28, 28, 36));
        panelRound1.setForeground(new java.awt.Color(28, 28, 36));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Regiones");

        panelRound2.setBackground(new java.awt.Color(19, 19, 26));
        panelRound2.setForeground(new java.awt.Color(28, 28, 36));
        panelRound2.setRoundBottomLeft(15);
        panelRound2.setRoundBottomRight(15);
        panelRound2.setRoundTopLeft(15);
        panelRound2.setRoundTopRight(15);

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo");

        txtCodigo.setBackground(new java.awt.Color(40, 41, 52));
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de la Región");

        txtNombreR.setBackground(new java.awt.Color(40, 41, 52));
        txtNombreR.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreR.setBorder(null);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio Estandar");

        txtPrecioEst.setBackground(new java.awt.Color(40, 41, 52));
        txtPrecioEst.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioEst.setBorder(null);
        txtPrecioEst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioEstKeyReleased(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio Especial");

        txtPrecioEspe.setBackground(new java.awt.Color(40, 41, 52));
        txtPrecioEspe.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioEspe.setBorder(null);

        lblPrecioEstandar.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioEstandar.setText("jLabel6");

        lblPrecioEspecial.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioEspecial.setText("jLabel6");

        buttonRound1.setText("Agregar Región");
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(224, 224, 224)
                                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)))
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                        .addComponent(txtPrecioEst))
                                    .addComponent(lblPrecioEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreR, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                    .addComponent(txtPrecioEspe)
                                    .addComponent(lblPrecioEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtNombreR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecioEspe, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(txtPrecioEst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio Estandar", "Precio Especial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla1);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
        // TODO add your handling code here:
        agregarRegion();
    }//GEN-LAST:event_buttonRound1ActionPerformed

    private void txtPrecioEstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioEstKeyReleased
        // TODO add your handling code here:
        //^[0-9]+[.,]{1,1}\[0]{2,2}$
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtPrecioEst.setEditable(false);
            lblPrecioEstandar.setText("Solo numeros");
        } else {
            txtPrecioEst.setEditable(true);
            lblPrecioEstandar.setText("");
        }
    }//GEN-LAST:event_txtPrecioEstKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Elementos.ButtonRound buttonRound1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPrecioEspecial;
    private javax.swing.JLabel lblPrecioEstandar;
    private Elementos.PanelRound panelRound1;
    private Elementos.PanelRound panelRound2;
    private Elementos.CutomTable.TableDark tabla1;
    private Elementos.CutomTable.TableDark tableDark1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombreR;
    private javax.swing.JTextField txtPrecioEspe;
    private javax.swing.JTextField txtPrecioEst;
    // End of variables declaration//GEN-END:variables
}
