package Elementos.CutomTable;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author mesoi
 */
public class PanelActioEliminar extends javax.swing.JPanel {

    /**
     * Creates new form PanelActioEliminar
     */
    public PanelActioEliminar() {
        initComponents();
    }
    
    public void initEvent(TableActionEvent event, int row) {
        cmdEliminar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdEliminar = new Elementos.ButtonRound();

        cmdEliminar.setBorder(null);
        cmdEliminar.setForeground(new java.awt.Color(255, 255, 255));
        cmdEliminar.setText("Eliminar Región");
        cmdEliminar.setBorderColor(new java.awt.Color(245, 118, 112));
        cmdEliminar.setColor(new java.awt.Color(245, 118, 112));
        cmdEliminar.setColorClick(new java.awt.Color(118, 66, 67));
        cmdEliminar.setColorOver(new java.awt.Color(118, 66, 67));
        cmdEliminar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmdEliminar.setRadius(15);
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Elementos.ButtonRound cmdEliminar;
    // End of variables declaration//GEN-END:variables
}
