package Componentes;

import Administrador.Regiones;
import Usuario.Usuario;
import Usuario.ctrlUsuarios;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mesoi
 */
public class AdminReporteUsuario extends javax.swing.JPanel {
    private DefaultTableModel modelo;
    private ArrayList<Usuario> totalUsuarios;
    /**
     * Creates new form AdminReporteUsuario
     */
    public AdminReporteUsuario() {
        initComponents();
        this.setBounds(0, 0, 710, 500);
        modelo = (DefaultTableModel) tableRU.getModel();
        totalUsuarios = (ArrayList<Usuario>) ctrlUsuarios.getTodUsuarios().clone();
    }
    
    public void ordenarRegiones() {
         modelo.setRowCount(0);
        if (totalUsuarios.size() > 0) {
            Collections.sort(totalUsuarios, new Comparator<Usuario>() {
                @Override
                public int compare(Usuario p1, Usuario p2) {
                    // Aqui esta el truco, ahora comparamos p2 con p1 y no al reves como antes
                    return new Integer(p2.getContadorEnvios()).compareTo(new Integer(p1.getContadorEnvios()));
                }
            });

            for (int i = 0; i < totalUsuarios.size(); i++) {
                if (totalUsuarios.get(i).getContadorEnvios() != 0) {
                    Object datos[] = new Object[4];
                    datos[0] = i+1;
                    datos[1] = totalUsuarios.get(i).getNombre();
                    datos[2] = totalUsuarios.get(i).getApellido();
                    datos[3] = totalUsuarios.get(i).getContadorEnvios();
                    modelo.addRow(datos);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Elementos.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRU = new Elementos.CutomTable.TableDark();

        setOpaque(false);

        panelRound1.setBackground(new java.awt.Color(28, 28, 36));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reporte de usuarios con más paquetes Enviados");

        tableRU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Apellido", "No. De paquetes"
            }
        ));
        jScrollPane1.setViewportView(tableRU);
        if (tableRU.getColumnModel().getColumnCount() > 0) {
            tableRU.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Elementos.PanelRound panelRound1;
    private Elementos.CutomTable.TableDark tableRU;
    // End of variables declaration//GEN-END:variables
}
