package Componentes;

import Administrador.Regiones;
import Administrador.ctrlRegiones;
import Usuario.Envios;
import Usuario.ctrlEnvios;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mesoi
 */
public class AdminReporteRegion extends javax.swing.JPanel {

    private DefaultTableModel modelo;
    private ArrayList<Regiones> totalRegiones;
    //private ArrayList<Envios> totalEnvios;

    /**
     * Creates new form AdminReporteRegion
     */
    public AdminReporteRegion() {
        initComponents();
        this.setBounds(0, 0, 710, 500);
        modelo = (DefaultTableModel) tableA.getModel();
        totalRegiones = (ArrayList<Regiones>) ctrlRegiones.getTodHistorial().clone();
        ordenarRegiones();
        
    }

    public void ordenarRegiones() {
        if (totalRegiones.size() > 0) {
            Collections.sort(totalRegiones, new Comparator<Regiones>() {
                @Override
                public int compare(Regiones p1, Regiones p2) {
                    // Aqui esta el truco, ahora comparamos p2 con p1 y no al reves como antes
                    return new Integer(p2.getContadorEnvios()).compareTo(new Integer(p1.getContadorEnvios()));
                }
            });

            for (int i = 0; i < totalRegiones.size(); i++) {
                if (totalRegiones.get(i).getContadorEnvios() != 0) {
                    Object datos[] = new Object[3];
                    datos[0] = i+1;
                    datos[1] = totalRegiones.get(i).getNombre();
                    datos[2] = totalRegiones.get(i).getContadorEnvios();
                    modelo.addRow(datos);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Elementos.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableA = new Elementos.CutomTable.TableDark();

        panelRound1.setBackground(new java.awt.Color(73, 76, 79));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel1.setText("Lista de Regiones con más Envios");

        tableA.setBackground(new java.awt.Color(0, 0, 0));
        tableA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Region", "Numero de Envios"
            }
        ));
        jScrollPane2.setViewportView(tableA);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private Elementos.PanelRound panelRound1;
    private Elementos.CutomTable.TableDark tableA;
    // End of variables declaration//GEN-END:variables
}
