package Componentes;

import Administrador.Regiones;
import Administrador.ctrlRegiones;
import Componentes.CRUD.AdminAgregarRegiones;
import Componentes.CRUD.AdminModificarRegion;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author mesoi
 */
public class AdminRegiones extends javax.swing.JPanel {

    public ArrayList<Regiones> regio;
    private AdminAgregarRegiones aAR;
    private AdminModificarRegion aMR;

    /**
     * Creates new form Regiones
     */
    public AdminRegiones() {
        initComponents();
        this.setBounds(0, 0, 710, 500);
        aAR = new AdminAgregarRegiones();
        aMR = new AdminModificarRegion();
        regio = ctrlRegiones.getTodasRegiones();
        Border bottomBorder = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(150, 157, 175));
        Border bottomBorder1 = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.RED);
        panelBackground.setBorder(bottomBorder);
        panelAgregar.setBorder(bottomBorder1);
       
        panelCrud.add(aAR);
        panelCrud.add(aMR);
        menuClick(aAR);
       // cargarDatos();
    }
    
     public void menuClick(JPanel panel) {
        aAR.setVisible(false);
        aMR.setVisible(false);

        panel.setVisible(true);
    }
   

    public void actualizarDatos(String codigo, int posicion, double precioEstandar, double precioEspecial) {
        boolean cambios = false;
        if (regio.get(posicion).getPrecioEstandar() != precioEstandar) {
            int opcion = 1;
            if (ctrlRegiones.cambiarPrecios(codigo, opcion, precioEstandar)) {
                cambios = true;
            }
        } else if (regio.get(posicion).getPrecioEspecial() != precioEspecial) {
            int opcion = 2;
            if (ctrlRegiones.cambiarPrecios(codigo, opcion, precioEspecial)) {
                cambios = true;
            }
        }

        if (cambios) {
            JOptionPane.showMessageDialog(null, "Cambios exitosos");
        }
       // cargarDatos();
    }

    public void enviarActaulizaciones(String codigo, int posicion, JTextField estandard, JTextField especial) {
        if (!(estandard.getText().equals("") || especial.getText().equals(""))) {
            double precioEndard = Double.parseDouble(estandard.getText());
            double precioEspe = Double.parseDouble(especial.getText());
            actualizarDatos(codigo, posicion, precioEndard, precioEspe);
        }else{
            JOptionPane.showMessageDialog(null, "Campo Vacio");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound3 = new Elementos.PanelRound();
        panelBackground = new javax.swing.JPanel();
        panelAgregar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelModificar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelCrud = new javax.swing.JPanel();

        panelRound3.setBackground(new java.awt.Color(69, 74, 78));

        panelBackground.setOpaque(false);
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAgregarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel4.setText("Agregar");
        panelAgregar.add(jLabel4);

        panelBackground.add(panelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 121, -1));

        panelModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelModificarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel5.setText("Modificar");
        panelModificar.add(jLabel5);

        panelBackground.add(panelModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 121, -1));

        panelCrud.setBackground(new java.awt.Color(255, 51, 153));
        panelCrud.setOpaque(false);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCrud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCrud, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseClicked
        // TODO add your handling code here:
        menuClick(aMR);
        aMR.cargarRegiones();
        aMR.cargarBoxRegiones();
        aMR.mostrarPrecios(1);
    }//GEN-LAST:event_panelModificarMouseClicked

    private void panelAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAgregarMouseClicked
        // TODO add your handling code here:
        menuClick(aAR);
        aAR.cargarRegiones();
    }//GEN-LAST:event_panelAgregarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelCrud;
    private javax.swing.JPanel panelModificar;
    private Elementos.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}
