package Interfaz;

import Administrador.Kioscos;
import Administrador.ctrlKioscos;
import Usuario.ctrlUsuarios;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.basic.BasicComboBoxUI;

/**
 *
 * @author mesoi
 */
public class agregarUsuarios extends javax.swing.JFrame {

    public ArrayList<Kioscos> kiosco;
    public String ruta;
    private static String[] nombrePaises = {"Alemania", "Argentina", "Belice", "Brasil", "Canadá", "China",
        "El Salvador", "España", "Guatemala", "Honduras", "Japón", "México", "Portugal", "Uruguay"};

    /**
     * Creates new form agregarUsuarios
     */
    public agregarUsuarios() {
        UIManager.put("TextField.caretForeground", new ColorUIResource(255, 255, 255));
        UIManager.put("ComboBox.selectionBackground", new ColorUIResource(57, 60, 72));
         UIManager.put("ComboBox.selectionForeground", new ColorUIResource(255, 255, 255));
        initComponents();
        this.setLocationRelativeTo(null);
        agregarBoxes();
        boxKiosco.setEnabled(false);
        kiosco = ctrlKioscos.getAllKioscos();
        cargarKioscos();
        jSeparator1.setBackground(new Color(0, 0, 0, 1));
        jSeparator2.setBackground(new Color(0, 0, 0, 1));
        jSeparator3.setBackground(new Color(0, 0, 0, 1));
        boxKiosco.setVisible(false);
        
    }

    public void cargarKioscos() {
        for (int i = 0; i < kiosco.size(); i++) {
            if (kiosco.get(i) != null) {
                String codeK = kiosco.get(i).getCodigoKioco();
                String nombreKiosco = kiosco.get(i).getNombreKiosco();
                boxKiosco.addItem(new Kioscos(kiosco.get(i).getCodigo(), kiosco.get(i).getNombre(), kiosco.get(i).getPrecioEstandar(), kiosco.get(i).getPrecioEspecial(), codeK, nombreKiosco));
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new Elementos.PanelRound();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblop1 = new javax.swing.JLabel();
        lblop2 = new javax.swing.JLabel();
        lblop3 = new javax.swing.JLabel();
        lblop4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        boxRol = new javax.swing.JComboBox<>();
        txtKiosco = new javax.swing.JLabel();
        boxKiosco = new javax.swing.JComboBox<>();
        txtContra = new javax.swing.JPasswordField();
        txtValidar = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        boxNacionalidad = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        boxGenero = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtAlias = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDPI = new javax.swing.JTextField();
        lblDpi = new javax.swing.JLabel();
        panelRound2 = new Elementos.PanelRound();
        btbRegistrar = new javax.swing.JButton();
        lblIniciarS = new javax.swing.JLabel();
        panelRound3 = new Elementos.PanelRound();
        panelImagen = new javax.swing.JPanel();
        lblimagen = new javax.swing.JLabel();
        btnSubir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 29, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Usuarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 150, -1));

        panelRound1.setBackground(new java.awt.Color(34, 37, 47));
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo Electronico");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(34, 37, 47));
        txtCorreo.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCorreo.setOpaque(false);
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });
        jPanel4.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 29, 340, 32));

        lblCorreo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, 20));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, 65, -1));

        txtNombre.setBackground(new java.awt.Color(34, 37, 47));
        txtNombre.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 116, 150, 33));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 93, 65, -1));

        txtApellido.setBackground(new java.awt.Color(34, 37, 47));
        txtApellido.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(null);
        jPanel4.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 116, 160, 30));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 167, 92, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Valida Contraseña");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 167, 125, -1));

        lblop1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblop1.setForeground(new java.awt.Color(255, 75, 76));
        lblop1.setText("Letras Mayúsculas");
        jPanel4.add(lblop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, 161, 23));

        lblop2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblop2.setForeground(new java.awt.Color(255, 75, 76));
        lblop2.setText("Letras Minúsculas");
        jPanel4.add(lblop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 238, 165, 23));

        lblop3.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblop3.setForeground(new java.awt.Color(255, 75, 76));
        lblop3.setText("Números");
        jPanel4.add(lblop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 267, 161, 23));

        lblop4.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblop4.setForeground(new java.awt.Color(255, 75, 76));
        lblop4.setText("Caracteres Especiales");
        jPanel4.add(lblop4, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 267, 161, 23));

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Rol");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 302, 41, -1));

        boxRol.setBackground(new java.awt.Color(34, 37, 47));
        boxRol.setForeground(new java.awt.Color(255, 255, 255));
        boxRol.setBorder(null);
        boxRol.setOpaque(false);
        boxRol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxRolItemStateChanged(evt);
            }
        });
        jPanel4.add(boxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 325, 161, 34));

        txtKiosco.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        txtKiosco.setForeground(new java.awt.Color(255, 255, 255));
        txtKiosco.setText("Kiosco");
        jPanel4.add(txtKiosco, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 302, 49, -1));

        boxKiosco.setBackground(new java.awt.Color(34, 37, 47));
        jPanel4.add(boxKiosco, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 325, 165, 34));

        txtContra.setBackground(new java.awt.Color(34, 37, 47));
        txtContra.setForeground(new java.awt.Color(255, 255, 255));
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraKeyReleased(evt);
            }
        });
        jPanel4.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 190, 161, 33));

        txtValidar.setBackground(new java.awt.Color(34, 37, 47));
        txtValidar.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 190, 165, 30));

        jSeparator1.setBackground(new java.awt.Color(63, 70, 84));
        jSeparator1.setForeground(new java.awt.Color(68, 75, 87));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 8));

        jSeparator2.setForeground(new java.awt.Color(68, 75, 87));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        jSeparator3.setForeground(new java.awt.Color(68, 75, 87));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, 10));

        jPanel3.add(jPanel4);

        jPanel5.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha de Nacimiento");

        txtFecha.setBackground(new java.awt.Color(34, 37, 47));
        txtFecha.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nacionalidad");

        boxNacionalidad.setBackground(new java.awt.Color(34, 37, 47));
        boxNacionalidad.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Genero");

        boxGenero.setBackground(new java.awt.Color(34, 37, 47));
        boxGenero.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sobrenombre (Alias)");

        txtAlias.setBackground(new java.awt.Color(34, 37, 47));
        txtAlias.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Telefono");

        txtTelefono.setBackground(new java.awt.Color(34, 37, 47));
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
        });

        lblTelefono.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DPI");

        txtDPI.setBackground(new java.awt.Color(34, 37, 47));
        txtDPI.setForeground(new java.awt.Color(255, 255, 255));
        txtDPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDPIKeyPressed(evt);
            }
        });

        lblDpi.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDpi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDPI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(boxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(boxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAlias, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefono)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(14, 14, 14))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 770, 410));

        panelRound2.setBackground(new java.awt.Color(34, 37, 47));
        panelRound2.setRoundBottomLeft(15);
        panelRound2.setRoundBottomRight(15);

        btbRegistrar.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        btbRegistrar.setText("Registrar");
        btbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRegistrarActionPerformed(evt);
            }
        });

        lblIniciarS.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        lblIniciarS.setText("Iniciar Sesión");
        lblIniciarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarSMouseClicked(evt);
            }
        });
        lblIniciarS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblIniciarSKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIniciarS)
                    .addComponent(btbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btbRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIniciarS)
                .addGap(12, 12, 12))
        );

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 770, 80));

        panelRound3.setBackground(new java.awt.Color(34, 37, 47));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);

        panelImagen.setBackground(new java.awt.Color(204, 204, 204));
        panelImagen.setOpaque(false);

        lblimagen.setMaximumSize(new java.awt.Dimension(120, 120));
        lblimagen.setMinimumSize(new java.awt.Dimension(1, 1));
        lblimagen.setPreferredSize(new java.awt.Dimension(110, 110));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagenLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimagen, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSubir.setText("Subir");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubir)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRegistrarActionPerformed
        // TODO add your handling code here:
        agregarUsuario();
    }//GEN-LAST:event_btbRegistrarActionPerformed

    private void lblIniciarSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblIniciarSKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIniciarSKeyPressed

    private void lblIniciarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSMouseClicked
        // TODO add your handling code here:
        login l = new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblIniciarSMouseClicked

    private void txtContraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyReleased
        // TODO add your handling code here:
        Pattern vMayus = Pattern.compile("^(?=.*[A-Z])");
        Pattern vMinus = Pattern.compile("^(?=.*[a-z])");
        Pattern vNum = Pattern.compile("^(?=.*[0-9])");
        Pattern vEspecial = Pattern.compile("^(?=.*[!#%&@*$_-])");
        Pattern[] exp = {vMayus, vMinus, vNum, vEspecial};
        JLabel[] labels = {lblop1, lblop2, lblop3, lblop4};
        for (int i = 0; i < exp.length; i++) {
            Matcher m = exp[i].matcher(String.valueOf(txtContra.getPassword()));
            if (m.find()) {
                labels[i].setForeground(new Color(99, 220, 147));
            } else {
                labels[i].setForeground(new Color(255, 75, 76));;
            }
        }
    }//GEN-LAST:event_txtContraKeyReleased

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtTelefono.setEditable(false);
            lblTelefono.setText("Solo numeros");
        } else {
            txtTelefono.setEditable(true);
            lblTelefono.setText("");
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtDPIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDPIKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtDPI.setEditable(false);
            lblDpi.setText("Solo numeros");
        } else {
            txtDPI.setEditable(true);
            lblDpi.setText("");
        }
    }//GEN-LAST:event_txtDPIKeyPressed

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        // TODO add your handling code here:
        Pattern vCorreo = Pattern.compile("^[^@]+@[^@]+\\.[a-zA-Z]{2,}$");
        Matcher m = vCorreo.matcher(txtCorreo.getText());
        if (!m.find()) {
            lblCorreo.setForeground(new Color(255, 75, 76));
            lblCorreo.setText("Ingrese un correo valido");
            jSeparator1.setForeground(new Color(255, 75, 76));
        } else {
            lblCorreo.setText("");
            jSeparator1.setForeground(new Color(143, 235, 170));
        }
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void boxRolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxRolItemStateChanged
        // TODO add your handling code here:
        if (boxRol.getSelectedIndex() == 2) {
            boxKiosco.setEnabled(true);
            boxKiosco.setVisible(true);
        } else {
            boxKiosco.setEnabled(false);
            boxKiosco.setVisible(false);
        }
    }//GEN-LAST:event_boxRolItemStateChanged

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
        ruta = "";
        JFileChooser archivos = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG & PNG", "jpg", "png");
        archivos.setFileFilter(filtrado);

        int respuesta = archivos.showOpenDialog(this);
        if (respuesta == archivos.APPROVE_OPTION) {
            ruta = archivos.getSelectedFile().getPath();
            /// Cargar la imagen original
            ImageIcon originalImageIcon = new ImageIcon(ruta);

            // Obtener el tamaño original de la imagen
            int originalImageWidth = originalImageIcon.getIconWidth();
            int originalImageHeight = originalImageIcon.getIconHeight();

            // Obtener el tamaño del JLabel
            int labelWidth = lblimagen.getWidth();
            int labelHeight = lblimagen.getHeight();

            // Calcular la relación de aspecto de la imagen original y del JLabel
            double originalImageAspectRatio = (double) originalImageWidth / originalImageHeight;
            double labelAspectRatio = (double) labelWidth / labelHeight;

            // Escalar la imagen si es necesario
            ImageIcon scaledImageIcon;
            if (originalImageAspectRatio > labelAspectRatio) {
                // La imagen es más ancha que el JLabel
                int scaledImageWidth = labelWidth;
                int scaledImageHeight = (int) (scaledImageWidth / originalImageAspectRatio);
                Image scaledImage = originalImageIcon.getImage().getScaledInstance(scaledImageWidth, scaledImageHeight, Image.SCALE_SMOOTH);
                scaledImageIcon = new ImageIcon(scaledImage);
            } else {
                // La imagen es más alta que el JLabel
                int scaledImageHeight = labelHeight;
                int scaledImageWidth = (int) (scaledImageHeight * originalImageAspectRatio);
                Image scaledImage = originalImageIcon.getImage().getScaledInstance(scaledImageWidth, scaledImageHeight, Image.SCALE_SMOOTH);
                scaledImageIcon = new ImageIcon(scaledImage);
            }
            // Establecer el ImageIcon escalado en el JLabel
            lblimagen.setIcon(scaledImageIcon);

        }
    }//GEN-LAST:event_btnSubirActionPerformed
    public void agregarUsuario() {

        Kioscos kioscoItem = (Kioscos) boxKiosco.getSelectedItem();

        String correo = txtCorreo.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String contra = String.valueOf(txtContra.getPassword());
        String verificar = String.valueOf(txtValidar.getPassword());
        String dpi = txtDPI.getText();
        int rol = boxRol.getSelectedIndex() + 1;
        String img = "s";
        String fecha = txtFecha.getText();
        String nacionalidad = boxNacionalidad.getSelectedItem().toString();
        String genero = boxGenero.getSelectedItem().toString();
        String alias = txtAlias.getText();
        String numero = txtTelefono.getText();
        int n = Integer.parseInt(numero);
        System.out.println("Hola");

        if (!correo.equals("") && !nombre.equals("") && !apellido.equals("") && !contra.equals("")
                && !verificar.equals("") && !dpi.equals("") && rol != 0 && !fecha.equals("")
                && !nacionalidad.equals("") && !genero.equals("") && !genero.equals("") && !alias.equals("") && !numero.equals("")) {
            if (contra.equals(verificar)) {
                if (ctrlUsuarios.nuevoUsuario(correo, nombre, apellido, contra, dpi, numero, genero, nacionalidad, alias, n, rol, img)) {
                    JOptionPane.showMessageDialog(null, "Usuario Agregado");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar el usuario");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Tiene un campo sin llenar");
        }

    }

    public void agregarBoxes() {
        boxGenero.addItem("Masculino");
        boxGenero.addItem("Femenino");

        for (String nombres : nombrePaises) {
            boxNacionalidad.addItem(nombres);
        }
        boxRol.addItem("Usuario Individual");
        boxRol.addItem("Usuario Empresarial");
        boxRol.addItem("Kiosko");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarUsuarios().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGenero;
    private javax.swing.JComboBox<Object> boxKiosco;
    private javax.swing.JComboBox<String> boxNacionalidad;
    private javax.swing.JComboBox<String> boxRol;
    private javax.swing.JButton btbRegistrar;
    private javax.swing.JButton btnSubir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDpi;
    private javax.swing.JLabel lblIniciarS;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JLabel lblop1;
    private javax.swing.JLabel lblop2;
    private javax.swing.JLabel lblop3;
    private javax.swing.JLabel lblop4;
    private javax.swing.JPanel panelImagen;
    private Elementos.PanelRound panelRound1;
    private Elementos.PanelRound panelRound2;
    private Elementos.PanelRound panelRound3;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDPI;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JLabel txtKiosco;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JPasswordField txtValidar;
    // End of variables declaration//GEN-END:variables
}
